registry: localhost:32000

postgres:
  namespace: postgres
  release: postgres

kafka:
  namespace: kafka
  release: kafka

redis:
  namespace: redis
  release: redis

minio:
  namespace: minio
  release: minio

rabbitmq:
  namespace: rabbitmq
  release: rabbitmq

clickhouse:
  namespace: clickhouse
  release: clickhouse

netdata:
  namespace: monitoring
  release: netdata
