global:
  security:
    allowInsecureImages: true

auth:
  username: "admin"
  # Important for upgrades/diff: reuse existing secret created by Makefile.
  existingPasswordSecret: rabbitmq
  existingErlangSecret: rabbitmq

image:
  registry: localhost:32000
  repository: bitnami/rabbitmq
  tag: "4.1.3-debian-12-r1"

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi

volumePermissions:
  enabled: false
  image:
    registry: localhost:32000
    repository: bitnami/os-shell
    tag: "12-debian-12-r50"

ingress:
  enabled: false
  ingressClassName: nginx
  hostname: rabbitmq.local
  path: /
  pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  tls: false
