#!/usr/bin/env bash
# Генерирует overlay `redis/values-<ENV>.acl.yaml` с блоком auth.acl.users из
# apps/registry.yaml + apps/conf/<APP>/<ENV>/. Overlay читается helmfile вторым
# values-файлом для release redis — Bitnami chart рендерит users.acl в ConfigMap
# уже с app-users, и рестарт пода (любой причины: helm upgrade, OOM, eviction,
# нода) сразу восстанавливает корректный ACL без дополнительного reconcile.
#
# Принцип: overlay — производное от merged config. `redis-acl-reconcile.sh`
# вызывает этот скрипт первым шагом и затем патчит живой ConfigMap содержимым,
# эквивалентным тому, что отрендерит helm с этим overlay. Это держит ConfigMap
# идемпотентным к helm upgrade.
#
# Env (обязательно): APPS_REGISTRY, REPO_ROOT, ENV.
# Env (опционально): APPS_MERGED_FILE (если уже подготовлен; иначе скрипт вычислит),
#                    OUTPUT_FILE (default: $REPO_ROOT/redis/values-$ENV.acl.yaml).
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
# shellcheck disable=SC1091
source "$SCRIPT_DIR/apps-yq-probe.sh"

REG="${APPS_REGISTRY:?APPS_REGISTRY required}"
REPO="${REPO_ROOT:?REPO_ROOT required}"
ENV="${ENV:?ENV required}"

OUT="${OUTPUT_FILE:-$REPO/redis/values-$ENV.acl.yaml}"

MERGED="${APPS_MERGED_FILE:-}"
CLEAN_MERGED=0
if [[ -z "$MERGED" ]]; then
	MERGED=$(mktemp)
	CLEAN_MERGED=1
	"$SCRIPT_DIR/apps-merge-config.sh" "$REG" "$REPO" "$ENV" >"$MERGED"
fi
trap '[[ "$CLEAN_MERGED" == "1" ]] && rm -f "$MERGED"' EXIT INT TERM

# Список запрещённых команд. Синхронен с scripts/redis-acl-reconcile.sh —
# при изменении правьте оба файла, иначе ConfigMap, отрендеренный helm с этим
# overlay, разойдётся с ConfigMap, который патчит reconcile, и любой helm
# upgrade будет триггерить rolling restart redis-master.
DENY="-ACL -CONFIG -SHUTDOWN -MODULE -DEBUG -COMMAND -KEYS -FLUSHALL -FLUSHDB -LATENCY -MEMORY -MONITOR -SAVE -BGSAVE -BGREWRITEAOF -REPLCONF -REPLICAOF -SLAVEOF -SYNC -PSYNC"

TMP=$(mktemp)
trap '[[ "$CLEAN_MERGED" == "1" ]] && rm -f "$MERGED"; rm -f "$TMP"' EXIT INT TERM

{
	cat <<'EOF'
# Auto-generated by scripts/redis-build-acl-overlay.sh — DO NOT EDIT.
# Source of truth: apps/registry.yaml + apps/conf/<APP>/<ENV>/.
# Regenerated on each `make up` / `apps-apply` / `redis-acl-reconcile`.
# Bitnami redis chart рендерит этот блок в ConfigMap redis-configuration
# поля users.acl (см. redis/redis/templates/configmap.yaml L51-69).
EOF
	printf 'auth:\n  acl:\n    users:'
} >"$TMP"

APP_COUNT=0
# Перебираем enabled-приложения с непустым redis.password.
# Поля: username (default app_<name>), password, keys (default ~<name>:*),
# channels (default &<name>:*). commands формируется как +@all <DENY>.
while IFS= read -r app; do
	[[ -n "$app" ]] || continue
	PW=$("$SCRIPT_DIR/app-config-get.sh" "$MERGED" "$app" redis.password 2>/dev/null || true)
	if [[ -z "$PW" || "$PW" == "null" ]]; then continue; fi

	USERNAME=$("$SCRIPT_DIR/app-config-get.sh" "$MERGED" "$app" redis.username 2>/dev/null || true)
	[[ -z "$USERNAME" || "$USERNAME" == "null" ]] && USERNAME="app_$app"

	KEY_PREFIX=$("$SCRIPT_DIR/app-config-get.sh" "$MERGED" "$app" redis.key_prefix 2>/dev/null || true)
	if [[ -z "$KEY_PREFIX" || "$KEY_PREFIX" == "null" ]]; then
		KEYS="~${app}:*"
		CHANNELS="&${app}:*"
	else
		# key_prefix у нас всегда оканчивается двоеточием (см. redis/Makefile app-create
		# REDIS_KEY_PREFIX=$(APP):). Для ACL keys/channels это уже корректный glob.
		KEYS="~${KEY_PREFIX}*"
		CHANNELS="&${KEY_PREFIX}*"
	fi

	# Используем yq для безопасного добавления записи в YAML-массив:
	# strenv() корректно квотирует значения, содержащие спецсимволы YAML.
	APP_USERNAME="$USERNAME" APP_PW="$PW" APP_KEYS="$KEYS" APP_CHANNELS="$CHANNELS" APP_CMDS="+@all $DENY" \
		"$YQBIN" -i '
			.auth.acl.users += [{
				"username": strenv(APP_USERNAME),
				"password": strenv(APP_PW),
				"keys": strenv(APP_KEYS),
				"channels": strenv(APP_CHANNELS),
				"commands": strenv(APP_CMDS)
			}]
		' "$TMP"
	APP_COUNT=$((APP_COUNT + 1))
done < <("$YQBIN" -r '.apps[] | select(.enabled == true) | .name' "$MERGED")

# Если ни одного app-user — оставляем явно пустой массив (`users: []`),
# чтобы helm не падал на nil при `range`.
if [[ "$APP_COUNT" -eq 0 ]]; then
	"$YQBIN" -i '.auth.acl.users = []' "$TMP"
fi

mkdir -p "$(dirname "$OUT")"

# Идемпотентность: если содержимое не изменилось — оставляем mtime файла,
# чтобы helm-diff/checksum/configuration не подёргивались по чужим причинам.
if [[ -f "$OUT" ]] && cmp -s "$TMP" "$OUT"; then
	echo "✓ redis ACL overlay без изменений: $OUT ($APP_COUNT app users)"
else
	mv "$TMP" "$OUT"
	echo "✓ redis ACL overlay записан: $OUT ($APP_COUNT app users)"
fi
